### ISSUE TITLE
Is it possible to add version file? and do tag for each version

### ISSUE THREAD

**Issue by 264768502** [ArchRobison/zapif#3]
Could we add one version file? Then add -v into main to show version.
And create tag for each release, and update version file meanwhile.

currently, our m y e l i n project require to use it for open source, and we decide to use zapif.
as we see, zapif is active project, if there is no version, it maybe hard for us to trace the issue which caused by zapif.

**Comment by ArchRobison** [comment]
Now implemented. 
* New file `version.txt`
* `-v` option causes the version to be printed on stderr.
* Tagged with `v1.1.0`
